### ISSUE TITLE
server error when accessing PG

### ISSUE THREAD

**Issue by EthanTodd** [Advenran/Adventure-Randomizer#3]
`Ethans-MacBook-Air:random_adv ET$ rake db:migrate
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?`
Anny i'm not sure why i am getting this error. This was after i did db:create.  typing in psql also does not allow me to enter pg

**Comment by annarankin** [comment]
Hey Ethan, is this specific to your machine? If so, have you restarted your computer recently?

**Comment by EthanTodd** [comment]
there was an osx update over the weekend and it restarted

**Comment by EthanTodd** [comment]
Also, i can't push :( ```nothing to commit, working directory clean
Ethans-MacBook-Air:random_adv ET$ git pull --rebase
You are not currently on a branch. Please specify which
branch you want to rebase against. See git-pull(1) for details.

```
git pull <remote> <branch>
```

Ethans-MacBook-Air:random_adv ET$ cd ..
Ethans-MacBook-Air:Adventure-Randomizer ET$ git add .
Ethans-MacBook-Air:Adventure-Randomizer ET$ git commit -m "edit form"
rebase in progress; onto c70c51e
You are currently rebasing branch 'master' on 'c70c51e'.

nothing to commit, working directory clean
Ethans-MacBook-Air:Adventure-Randomizer ET$ git checkout origin master
error: pathspec 'master' did not match any file(s) known to git.
Ethans-MacBook-Air:Adventure-Randomizer ET$ git checkout
Ethans-MacBook-Air:Adventure-Randomizer ET$ ```

**Comment by annarankin** [comment]
Gotcha -ok, there's most likely a problem with your pg server not having
shut down correctly - I'll come help you out in a little while, hang right
until then!
