### ISSUE TITLE
We can't seem to get our route to work correctly

### ISSUE THREAD

**Issue by EthanTodd** [Advenran/Adventure-Randomizer#8]
When the button is clicked for a new adventure the page should go to our adventure#show page however it keeps giving us all different errors.

We'd like to keep everything restful and make it work the right way

**Comment by annarankin** [comment]
Ok, that's odd - can you paste in your error messages here?

**Comment by EthanTodd** [comment]
```ActionController::UrlGenerationError in Adventures#new
Showing /Users/ET/dev/wpi/projThree/Adventure-Randomizer/random_adv/app/views/adventures/new.html.erb where line #24 raised:

No route matches {:action=>"show", :controller=>"adventures", :user_id=>"3"} missing required keys: [:id]``` this is one of them

**Comment by EthanTodd** [comment]
there have been a bunch, each time we think we've fixed it there is another error to follow. it looks to be trying to render a post method and we aren't sure why

**Comment by annarankin** [comment]
Ok, I'll come down soon

**Comment by EthanTodd** [comment]
Anna, we have tried pair coding to get this route issue working and we still can't seem to do it. Matt and I tried it and then handed off to Sam and David. The routes seem correct but, but it seems to be grabbing the response before it's available?

**Comment by EthanTodd** [comment]
it keeps asking for a view coupled with 'create'
